In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
import os
import csv
%matplotlib inline

In [2]:
os.chdir ("C:\Python")

In [4]:
dataset = pd.read_csv('Degree of ill.csv')
dataset

Retardation  Distrust  Degree of Illness
0          2.80       6.1                 44
1          3.10       5.1                 25
2          2.59       6.0                 10
3          3.36       6.9                 28
4          2.80       7.0                 25
5          3.35       5.6                 72
6          2.99       6.3                 45
7          2.99       7.2                 25
8          2.92       6.9                 12
9          3.23       6.5                 24
10         3.37       6.8                 46
11         2.72       6.6                  8
12         3.47       8.4                 15
13         2.70       5.9                 28
14         3.24       6.0                 26
15         2.65       6.0                 27
16         3.41       7.6                  4
17         2.58       6.2                 14
18         2.81       6.0                 21
19         2.80       6.4                 22
20         3.62       6.8                 60
21         2.74       8.4                 10
22         3.27       6.7                 60
23         3.78       8.3                 12
24         2.90       5.6                 28
25         3.70       7.3                 39
26         3.40       7.0                 14
27         2.63       6.9                  8
28         2.65       5.8                 11
29         3.26       7.2                  7
30         3.15       6.5                 23
31         2.60       6.3                 16
32         2.74       6.8                 26
33         2.72       5.9                  8
34         3.11       6.8                 11
35         2.79       6.7                 12
36         2.90       6.7                 50
37         2.74       5.5                  9
38         2.70       6.9                 13
39         3.08       6.3                 22
40         2.18       6.1                 23
41         2.88       5.8                 31
42         3.04       6.8                 20
43         3.32       7.3                 66
44         2.80       5.9                  9
45         3.29       6.8                 12
46         3.56       8.8                 21
47         2.74       7.1                 13
48         3.06       6.9                 10
49         2.54       6.7                  4
50         2.78       7.2                 18
51         2.81       5.2                 10
52         3.26       6.6                  7

In [5]:
X = dataset.iloc[:,:-1].values
Y = dataset.iloc[:,2].values

In [6]:
X

array([[2.8 , 6.1 ],
       [3.1 , 5.1 ],
       [2.59, 6.  ],
       [3.36, 6.9 ],
       [2.8 , 7.  ],
       [3.35, 5.6 ],
       [2.99, 6.3 ],
       [2.99, 7.2 ],
       [2.92, 6.9 ],
       [3.23, 6.5 ],
       [3.37, 6.8 ],
       [2.72, 6.6 ],
       [3.47, 8.4 ],
       [2.7 , 5.9 ],
       [3.24, 6.  ],
       [2.65, 6.  ],
       [3.41, 7.6 ],
       [2.58, 6.2 ],
       [2.81, 6.  ],
       [2.8 , 6.4 ],
       [3.62, 6.8 ],
       [2.74, 8.4 ],
       [3.27, 6.7 ],
       [3.78, 8.3 ],
       [2.9 , 5.6 ],
       [3.7 , 7.3 ],
       [3.4 , 7.  ],
       [2.63, 6.9 ],
       [2.65, 5.8 ],
       [3.26, 7.2 ],
       [3.15, 6.5 ],
       [2.6 , 6.3 ],
       [2.74, 6.8 ],
       [2.72, 5.9 ],
       [3.11, 6.8 ],
       [2.79, 6.7 ],
       [2.9 , 6.7 ],
       [2.74, 5.5 ],
       [2.7 , 6.9 ],
       [3.08, 6.3 ],
       [2.18, 6.1 ],
       [2.88, 5.8 ],
       [3.04, 6.8 ],
       [3.32, 7.3 ],
       [2.8 , 5.9 ],
       [3.29, 6.8 ],
       [3.56, 8.8 ],
       [2.74,

In [7]:
Y

array([44, 25, 10, 28, 25, 72, 45, 25, 12, 24, 46,  8, 15, 28, 26, 27,  4,
       14, 21, 22, 60, 10, 60, 12, 28, 39, 14,  8, 11,  7, 23, 16, 26,  8,
       11, 12, 50,  9, 13, 22, 23, 31, 20, 66,  9, 12, 21, 13, 10,  4, 18,
       10,  7], dtype=int64)

In [8]:
import numpy as np
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 1/3,random_state = 0)

In [9]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [18]:
Y_pred = regressor.predict(X_test)
Y_pred

array([23.58746092, 15.76915762, 14.08121501, 23.04006904, 17.06068177,
       19.47620147, 17.12204303, 27.22924494, 23.19104246, 27.81754432,
       15.3113779 , 28.90063237, 12.62216226, 28.31623155, 26.87763256,
       26.87373398, 27.67046948, 17.56326757])

In [11]:
X_train

array([[3.24, 6.  ],
       [3.11, 6.8 ],
       [3.06, 6.9 ],
       [2.81, 6.  ],
       [2.78, 7.2 ],
       [2.79, 6.7 ],
       [2.65, 6.  ],
       [3.35, 5.6 ],
       [2.65, 5.8 ],
       [3.41, 7.6 ],
       [3.29, 6.8 ],
       [3.62, 6.8 ],
       [3.56, 8.8 ],
       [2.92, 6.9 ],
       [2.7 , 5.9 ],
       [3.7 , 7.3 ],
       [2.58, 6.2 ],
       [2.81, 5.2 ],
       [3.04, 6.8 ],
       [3.1 , 5.1 ],
       [3.47, 8.4 ],
       [2.18, 6.1 ],
       [2.9 , 5.6 ],
       [2.99, 6.3 ],
       [3.78, 8.3 ],
       [2.9 , 6.7 ],
       [2.74, 8.4 ],
       [2.8 , 6.4 ],
       [3.23, 6.5 ],
       [3.08, 6.3 ],
       [2.54, 6.7 ],
       [3.36, 6.9 ],
       [2.8 , 6.1 ],
       [2.74, 7.1 ],
       [2.8 , 5.9 ]])

In [12]:
Y_train

array([26, 11, 10, 21, 18, 12, 27, 72, 11,  4, 12, 60, 21, 12, 28, 39, 14,
       10, 20, 25, 15, 23, 28, 45, 12, 50, 10, 22, 24, 22,  4, 28, 44, 13,
        9], dtype=int64)

In [19]:
Y_pred = regressor.predict(X[[4]])
Y_pred

array([15.3113779])