In [1]:
#importin library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import csv

In [3]:
#getting data
df = pd.read_csv('Real estate valuation data set.csv')
df

transaction date  house age   distance to the nearest MRT station  \
0             2012.917       32.0                              84.87882   
1             2012.917       19.5                             306.59470   
2             2013.583       13.3                             561.98450   
3             2013.500       13.3                             561.98450   
4             2012.833        5.0                             390.56840   
5             2012.667        7.1                            2175.03000   
6             2012.667       34.5                             623.47310   
7             2013.417       20.3                             287.60250   
8             2013.500       31.7                            5512.03800   
9             2013.417       17.9                            1783.18000   
10            2013.083       34.8                             405.21340   
11            2013.333        6.3                              90.45606   
12            2012.917       13.0                             492.23130   
13            2012.667       20.4                            2469.64500   
14            2013.500       13.2                            1164.83800   
15            2013.583       35.7                             579.20830   
16            2013.250        0.0                             292.99780   
17            2012.750       17.7                             350.85150   
18            2013.417       16.9                             368.13630   
19            2012.667        1.5                              23.38284   
20            2013.417        4.5                            2275.87700   
21            2013.417       10.5                             279.17260   
22            2012.917       14.7                            1360.13900   
23            2013.083       10.1                             279.17260   
24            2013.000       39.6                             480.69770   
25            2013.083       29.3                            1487.86800   
26            2012.667        3.1                             383.86240   
27            2013.250       10.4                             276.44900   
28            2013.500       19.2                             557.47800   
29            2013.083        7.1                             451.24380   
..                 ...        ...                                   ...   
384           2012.750       16.1                            4066.58700   
385           2013.000       18.3                              82.88643   
386           2012.833        0.0                             185.42960   
387           2013.250       16.2                            2103.55500   
388           2013.500       10.4                            2251.93800   
389           2013.250       40.9                             122.36190   
390           2013.500       32.8                             377.83020   
391           2013.583        6.2                            1939.74900   
392           2013.083       42.7                             443.80200   
393           2013.000       16.9                             967.40000   
394           2013.500       32.6                            4136.27100   
395           2012.917       21.2                             512.54870   
396           2012.667       37.1                             918.63570   
397           2013.417       13.1                            1164.83800   
398           2013.417       14.7                            1717.19300   
399           2012.917       12.7                             170.12890   
400           2013.250       26.8                             482.75810   
401           2013.083        7.6                            2175.03000   
402           2012.833       12.7                             187.48230   
403           2012.667       30.9                             161.94200   
404           2013.333       16.4                             289.32480   
405           2012.667       23

In [4]:
#data exploration
#there is no categorical variable
df.head()

transaction date  house age   distance to the nearest MRT station  \
0           2012.917       32.0                              84.87882   
1           2012.917       19.5                             306.59470   
2           2013.583       13.3                             561.98450   
3           2013.500       13.3                             561.98450   
4           2012.833        5.0                             390.56840   

    number of convenience stores  latitude   longitude  \
0                             10  24.98298   121.54024   
1                              9  24.98034   121.53951   
2                              5  24.98746   121.54391   
3                              5  24.98746   121.54391   
4                              5  24.97937   121.54245   

   house price of unit area  
0                      37.9  
1                      42.2  
2                      47.3  
3                      54.8  
4                      43.1

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 414 entries, 0 to 413
Data columns (total 7 columns):
 transaction date                       414 non-null float64
house age                               414 non-null float64
 distance to the nearest MRT station    414 non-null float64
 number of convenience stores           414 non-null int64
latitude                                414 non-null float64
 longitude                              414 non-null float64
house price of unit area                414 non-null float64
dtypes: float64(6), int64(1)
memory usage: 22.7 KB


In [5]:
#Data cleaning - imputing missing value
#checking missing data -print(df.isnull())
# count the number of NaN values in each column
print(df.isnull().sum())
#df.apply(lambda x: sum(x.isnull()))


 transaction date                       0
house age                               0
 distance to the nearest MRT station    0
 number of convenience stores           0
latitude                                0
 longitude                              0
house price of unit area                0
dtype: int64


In [6]:
#finding unique vale in data frame
df.nunique().sum()

1254

In [7]:
df.apply(lambda x: len(x.unique()))


 transaction date                        12
house age                               236
 distance to the nearest MRT station    259
 number of convenience stores            11
latitude                                234
 longitude                              232
house price of unit area                270
dtype: int64

In [8]:
#statistical descriptons
df.describe()


transaction date   house age   distance to the nearest MRT station  \
count         414.000000  414.000000                            414.000000   
mean         2013.148971   17.712560                           1083.885689   
std             0.281967   11.392485                           1262.109595   
min          2012.667000    0.000000                             23.382840   
25%          2012.917000    9.025000                            289.324800   
50%          2013.167000   16.100000                            492.231300   
75%          2013.417000   28.150000                           1454.279000   
max          2013.583000   43.800000                           6488.021000   

        number of convenience stores    latitude   longitude  \
count                     414.000000  414.000000  414.000000   
mean                        4.094203   24.969030  121.533361   
std                         2.945562    0.012410    0.015347   
min                         0.000000   24.932070  121.473530   
25%                         1.000000   24.963000  121.528085   
50%                         4.000000   24.971100  121.538630   
75%                         6.000000   24.977455  121.543305   
max                        10.000000   25.014590  121.566270   

       house price of unit area  
count                414.000000  
mean                  37.980193  
std                   13.606488  
min                    7.600000  
25%                   27.700000  
50%                   38.450000  
75%                   46.600000  
max                  117.500000

In [15]:
#feature scaling- in this data set ever data is in same scale

In [9]:
#Importing the independent data set 
X = df.iloc[:,:-1].values
X

array([[2012.917  ,   32.     ,   84.87882,   10.     ,   24.98298,
         121.54024],
       [2012.917  ,   19.5    ,  306.5947 ,    9.     ,   24.98034,
         121.53951],
       [2013.583  ,   13.3    ,  561.9845 ,    5.     ,   24.98746,
         121.54391],
       ...,
       [2013.25   ,   18.8    ,  390.9696 ,    7.     ,   24.97923,
         121.53986],
       [2013.     ,    8.1    ,  104.8101 ,    5.     ,   24.96674,
         121.54067],
       [2013.5    ,    6.5    ,   90.45606,    9.     ,   24.97433,
         121.5431 ]])

In [10]:
#importing the dependent data set
Y = df.iloc[:,6].values
Y

array([ 37.9,  42.2,  47.3,  54.8,  43.1,  32.1,  40.3,  46.7,  18.8,
        22.1,  41.4,  58.1,  39.3,  23.8,  34.3,  50.5,  70.1,  37.4,
        42.3,  47.7,  29.3,  51.6,  24.6,  47.9,  38.8,  27. ,  56.2,
        33.6,  47. ,  57.1,  22.1,  25. ,  34.2,  49.3,  55.1,  27.3,
        22.9,  25.3,  47.7,  46.2,  15.9,  18.2,  34.7,  34.1,  53.9,
        38.3,  42. ,  61.5,  13.4,  13.2,  44.2,  20.7,  27. ,  38.9,
        51.7,  13.7,  41.9,  53.5,  22.6,  42.4,  21.3,  63.2,  27.7,
        55. ,  25.3,  44.3,  50.7,  56.8,  36.2,  42. ,  59. ,  40.8,
        36.3,  20. ,  54.4,  29.5,  36.8,  25.6,  29.8,  26.5,  40.3,
        36.8,  48.1,  17.7,  43.7,  50.8,  27. ,  18.3,  48. ,  25.3,
        45.4,  43.2,  21.8,  16.1,  41. ,  51.8,  59.5,  34.6,  51. ,
        62.2,  38.2,  32.9,  54.4,  45.7,  30.5,  71. ,  47.1,  26.6,
        34.1,  28.4,  51.6,  39.4,  23.1,   7.6,  53.3,  46.4,  12.2,
        13. ,  30.6,  59.6,  31.3,  48. ,  32.5,  45.5,  57.4,  48.6,
        62.9,  55. ,

In [11]:
#spliting the dataset into Training Set and Testing set
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 1/3,random_state = 0)

In [12]:
X_train

array([[2.0132500e+03, 2.2200000e+01, 3.7955750e+02, 1.0000000e+01,
        2.4983430e+01, 1.2153762e+02],
       [2.0130000e+03, 1.0000000e+00, 1.9358450e+02, 6.0000000e+00,
        2.4965710e+01, 1.2154089e+02],
       [2.0130000e+03, 1.3200000e+01, 4.9223130e+02, 5.0000000e+00,
        2.4965150e+01, 1.2153737e+02],
       ...,
       [2.0130000e+03, 1.3600000e+01, 4.1973490e+03, 0.0000000e+00,
        2.4938850e+01, 1.2150383e+02],
       [2.0135830e+03, 3.5900000e+01, 6.4073910e+02, 3.0000000e+00,
        2.4975630e+01, 1.2153715e+02],
       [2.0135830e+03, 6.6000000e+00, 9.0456060e+01, 9.0000000e+00,
        2.4974330e+01, 1.2154310e+02]])

In [13]:
Y_train

array([ 44. ,  50.7,  42.3,  36.5,  51.4,  32.9,  38.6,  21.4,  50.4,
        37.4,  52.2,  58.8,  43.8,  22.1,  53.3,  17.4,  45.7,  36.6,
        39.7,  15.4,  12.2,  46.6,  31.3,  22.3,  23.1,  17.4,  46.8,
        32.9,  62.9,  25.5,  42.2,  42.5,  39.5,  49.3,  31.3,  11.6,
        55.1,  19. ,  34.6,  50.8,  63.2,  43.4,  35.1,  27.3,  41.2,
        37.2,  23.1,  14.7,  34.1,  37.5,  42. ,  25.6,  53.3,  41.4,
        20. ,  47.4,  24.7,  38.5,  49. ,  57.1,  55.9,  36.9,  25.6,
        20.7,  37. ,  29.5,  33.6,  47.3,  23.9,  18.3,  35.7,  67.7,
        40.6,  43.5,  31.1,  51.8,  61.9,  56.3,  63.3,  48.1,  18.6,
        20.5,  20.9,  27.3,  26.6,  34. ,  52.2,  56.8,  38.8,  44. ,
        39.7,  53.9,  30.6,  42.3,  41. ,  16.1,  39.4,  73.6,  44.5,
        36.7,  30.5,  15.9,  42.3,  34.1,  26.5,  24.4,  31.7,  40.8,
        23.8,  28.6,  58. ,  37.3,  42.9,  28.1,  46.6,  57.8,  30.5,
        39.6,  17.7,  40.6,  27.3,  51.6,  39.7,  28.9,  70.1,  45.4,
        28.4,  11.2,

In [70]:
# Model Building

In [14]:
#Fitting Multiple Linear Regression to The Training Set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [15]:
#Predicting The test set result
y_pred = regressor.predict(X_test)
y_pred

array([40.87811266, 12.56646611, 42.54990116, 12.3979175 , 43.12062788,
       40.09320113, 40.80009517, 34.57081547, 49.77913902, 46.47046629,
       46.06952221, 40.76924262, 40.28476746, 40.29724432, 47.67572246,
       38.74755077, 40.37031959, 41.88184196, 41.15469513, 42.86461775,
       50.11115583, 31.14656097, 40.56556864, 46.25115789, 46.75877961,
       43.70537213, 46.55533351, 26.60141762, 48.76042236, 21.59439122,
       44.82442924, 35.33618117, 43.45552574, 39.15611041, 44.25004041,
       32.31235943, 48.09849406, 40.21985603, 53.08548878,  7.31841346,
       52.67406499, 33.86202343, 34.69426506, 50.01976217, 14.99254492,
       43.31460482, 42.98867354, 12.73772855, 34.23232491, 48.47931372,
       53.96045439, 39.32493637, 48.24680065, 25.46988969, 30.76348034,
       34.75866859, 49.57115497, 41.12713922, 43.73792528, 33.40909508,
       44.27830477, 44.0277985 , 40.29816151, 47.50014974, 37.19006435,
       30.20600884,  9.48887973, 35.39478373, 46.91395869, 40.09

In [ ]:
"""We know that the equation of a mutliple linear regression line is given by y=b1+b2*x+b3*x’+b4*x”+…….
where b1, b2, b3, … are the coefficients and x, x’, x” are all independent variables.
Since we dont have any ‘x’ for the first coefficient we assume it can be written as a product of b and 1 and hence we append a column of ones. There are libraries that take care of it but since we are using the stats model library we need to explicitly add the column.""""

In [17]:
# building the optimal model using backward elimination
# SL = 0.05 and eliminating those features which have p > SL
import statsmodels.formula.api as sm
X= np.append(arr = np.ones((414,1)).astype(int), values = X, axis = 1)
#np.append(x, x[:,-1:], axis=1)

In [18]:
#independent variables that are statistically significant for dependent variable so now creating optimal matrix
X_opt = X[:,[0,1,2,3,4,5]]
regressor_ols = sm.OLS(endog = Y, exog = X_opt).fit()

In [19]:
#Here important to know lower is the p-value the more significant our independent is going to be with respect to dependent variable. 
regressor_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.582
Model:                            OLS   Adj. R-squared:                  0.577
Method:                 Least Squares   F-statistic:                     113.8
Date:                Sat, 21 Dec 2019   Prob (F-statistic):           4.47e-75
Time:                        23:19:56   Log-Likelihood:                -1487.0
No. Observations:                 414   AIC:                             2986.
Df Residuals:                     408   BIC:                             3010.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -1.596e+04   3233.450     -4.936      0.000   -2.23e+04   -9602.961
x1             5.1348      1.555      3.303      0.001       2.079       8.191
x2            -0.2694      0.038     -7.003      0.000      -0.345      -0.194
x3            -0.0044      0.000     -8.887      0.000      -0.005      -0.003
x4             1.1361      0.188      6.056      0.000       0.767       1.505
x5           226.8816     44.174      5.136      0.000     140.044     313.719
==============================================================================
Omnibus:                      232.810   Durbin-Watson:                   2.154
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             3644.713
Skew:                           2.038   Prob(JB):                         0.00
Kurtosis:                      16.953   Cond. No.                     1.77e+07
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.77e+07. This might indicate that there are
strong multicollinearity or other numerical problems.
"""